export const DifficultyLevel = {
  BEGINNER: 'beginner',
  INTERMEDIATE: 'intermediate',
  ADVANCED: 'advanced',
} as const;

export type DifficultyLevel = (typeof DifficultyLevel)[keyof typeof DifficultyLevel];

export interface CurriculumTier {
  level: DifficultyLevel;
  label: string;
  description: string;
  vocabulary: string[];
  grammarTopics: string[];
  expectedSkills: string[];
  gradingLeniency: number;
}

export const CURRICULUM: Record<DifficultyLevel, CurriculumTier> = {
  [DifficultyLevel.BEGINNER]: {
    level: DifficultyLevel.BEGINNER,
    label: 'Beginner',
    description: 'Simple greetings, introductions, and basic directions. Focus on common courtesies and simple statements.',
    vocabulary: [
      'Здравствуйте', 'Привет', 'До свидания', 'Пока',
      'Доброе утро', 'Добрый день', 'Добрый вечер',
      'Спасибо', 'Пожалуйста', 'Извините', 'Простите',
      'Да', 'Нет', 'Хорошо', 'Плохо',
      'Меня зовут...', 'Как вас зовут?', 'Как дела?',
      'Мужчина', 'Женщина', 'Человек',
      'Дом', 'Книга', 'Окно', 'Стол', 'Стул',
      'Мама', 'Папа', 'Брат', 'Сестра',
      'Я', 'Ты', 'Он', 'Она', 'Оно', 'Мы', 'Вы', 'Они',
      'Большой', 'Маленький', 'Хороший', 'Плохой',
      'Красивый', 'Новый', 'Старый',
      'Один', 'Два', 'Три', 'Четыре', 'Пять',
      'Вот', 'Это', 'Где', 'Кто', 'Что',
    ],
    grammarTopics: [
      'Russian alphabet and sounds',
      'Gender of nouns (masculine, feminine, neuter)',
      'Hard and soft stems',
      'Personal pronouns (я, ты, он, она, оно, мы, вы, они)',
      'Formal vs informal: ты vs Вы',
      'Nominative plural of nouns',
      'No verb "to be" in present tense',
      'No articles (the/a)',
      'Basic stress and vowel reduction',
      'Conjunctions и (and) and а (but/and)',
    ],
    expectedSkills: [
      'Read Cyrillic aloud',
      'Greet people and say goodbye',
      'Introduce yourself and ask someone\'s name',
      'Ask "How are you?" and reply',
      'Identify gender of nouns by ending',
      'Replace nouns with pronouns (он/она/оно)',
      'Form basic nominative plural',
      'Use ты vs Вы appropriately',
    ],
    gradingLeniency: 15,
  },

  [DifficultyLevel.INTERMEDIATE]: {
    level: DifficultyLevel.INTERMEDIATE,
    label: 'Intermediate',
    description: 'Personal introductions, family, studies, and locations. Practice describing yourself and your background.',
    vocabulary: [
      'Мой', 'Моя', 'Моё', 'Мои', 'Твой', 'Наш', 'Ваш',
      'Семья', 'Родители', 'Дети', 'Муж', 'Жена',
      'Работа', 'Учиться', 'Учить', 'Говорить',
      'Русский язык', 'По-русски', 'Английский',
      'Школа', 'Университет', 'Студент', 'Учитель',
      'Город', 'Страна', 'Улица', 'Музей', 'Театр',
      'Аэропорт', 'Вокзал', 'Билет', 'Паспорт',
      'Ресторан', 'Магазин', 'Кафе', 'Больница',
      'Хотеть', 'Мочь', 'Знать', 'Понимать',
      'Читать', 'Писать', 'Слушать', 'Видеть',
      'Идти', 'Ехать', 'Быть', 'Жить',
      'Где', 'Куда', 'Откуда', 'Когда', 'Почему',
      'Потому что', 'Чтобы', 'Если',
      'Этот', 'Эта', 'Это', 'Эти', 'Тот', 'Та', 'То', 'Те',
      'Большой', 'Маленький', 'Новый', 'Старый', 'Хороший', 'Плохой',
      'Красивый', 'Интересный', 'Трудный', 'Лёгкий',
      'Одежда', 'Платье', 'Рубашка', 'Пальто',
      'Синий', 'Красный', 'Белый', 'Чёрный', 'Зелёный',
    ],
    grammarTopics: [
      'Possessive pronouns (мой, твой, наш, ваш)',
      'Prepositional case for location (в, на, о)',
      'Adjectives in nominative case',
      'Demonstrative pronouns (этот, тот)',
      'Verb conjugation: present tense (1st and 2nd conjugation)',
      'Past tense of verbs',
      'Accusative case for direct objects',
      'Verb хотеть (to want)',
      'Adverbs vs adjectives (какой vs как)',
      'Preposition о/об (about)',
      '-ся verbs (учиться, заниматься)',
      'Talking about languages (русский, по-русски)',
    ],
    expectedSkills: [
      'Talk about family and possessions',
      'Describe location using prepositional case',
      'Conjugate regular verbs in present tense',
      'Form past tense sentences',
      'Use accusative case for direct objects',
      'Describe people and objects with adjectives',
      'Ask and answer Where/Where to/Where from',
      'Express wants and ability',
      'Order food at a cafe/restaurant',
      'Ask for and give directions',
    ],
    gradingLeniency: 8,
  },

  [DifficultyLevel.ADVANCED]: {
    level: DifficultyLevel.ADVANCED,
    label: 'Advanced',
    description: 'Market shopping, cooking, bargaining, and making plans. Handle more complex transactions with expressive language.',
    vocabulary: [
      'Должен', 'Должна', 'Должны', 'Можно', 'Нельзя', 'Нужно',
      'Надо', 'Свободен', 'Занят', 'Готов',
      'Мне нравится', 'Я люблю', 'Я предпочитаю',
      'Идти', 'Ходить', 'Ехать', 'Ездить', 'Пойти', 'Поехать',
      'Спрашивать/Спросить', 'Говорить/Сказать',
      'Покупать/Купить', 'Давать/Дать',
      'Делать/Сделать', 'Понимать/Понять',
      'Видеть/Увидеть', 'Брать/Взять',
      'Продукты', 'Мясо', 'Рыба', 'Овощи', 'Фрукты',
      'Хлеб', 'Молоко', 'Сыр', 'Масло', 'Яйцо', 'Сахар',
      'Чай', 'Кофе', 'Вода', 'Сок', 'Вино', 'Пиво',
      'Магазин', 'Рынок', 'Касса', 'Цена', 'Деньги',
      'Друг', 'Подруга', 'Знакомый', 'Сосед', 'Коллега',
      'Кем работать', 'Куда пойти', 'Что делать',
      'Если бы', 'Чтобы', 'Который',
      'Нравиться', 'Казаться', 'Стараться',
      'Свой', 'Чей', 'Чья', 'Чьё', 'Чьи',
    ],
    grammarTopics: [
      'Irregular plural nouns',
      'Genitive case: possession, absence, quantity',
      'Dative case: indirect objects, age, necessity',
      'Instrumental case: with whom, by what means',
      'Verbal aspect: perfective vs imperfective',
      'Verbs of going: идти/ходить, ехать/ездить',
      'Short-form adjectives (должен, занят, свободен)',
      'Dative subjectless expressions (мне нужно, мне холодно)',
      'Expressing likes/dislikes (нравится vs любить)',
      'Prepositional case with adjectives and pronouns',
      'Expressing necessity, possibility, permission',
      'Complex sentences with который, если бы, чтобы',
    ],
    expectedSkills: [
      'Express necessity and obligation (должен, нужно)',
      'Talk about food, shopping, and prices',
      'Use genitive case for possession and absence',
      'Use dative case for giving and age',
      'Use instrumental case for means and companionship',
      'Choose correct verb aspect (perfective vs imperfective)',
      'Use unidirectional and multidirectional going verbs',
      'Express likes, dislikes, and preferences',
      'Give and receive gifts using appropriate vocabulary',
      'Handle complex multi-clause conversations',
    ],
    gradingLeniency: 0,
  },
};
